CREATE TABLE IF NOT EXISTS review_hold (
unique_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
nickname VARCHAR(50) NOT NULL, 
email VARCHAR(50) NOT NULL,
rating VARCHAR(1) NOT NULL,  
ReviewTitle VARCHAR(60) NOT NULL,
message TEXT(500) NOT NULL, 
reg_date DATETIME NOT NULL, 
modStatus VARCHAR(4) NOT NULL,
CCR_id VARCHAR(60) NOT NULL,
recommend VARCHAR(3) NOT NULL,
PRIMARY KEY (unique_id));